version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_press
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/src
    stdin_open: true
    tty: true